zdanovich_lesson_11
alex-zdns/handh.school.homework pull request #13
Opened 2021-04-28 16:06 UTC by alex-zdns

2021-04-28 17:35 UTC, Artem2186 requested changes

2021-04-28 17:35 UTC, Artem2186 commented on zdanovich_lesson_11/app/src/main/res/layout/activity_main.xml
> +    <ru.zdanovich.handhSchoolHomework.views.ColumnChartView
почистить xml

2021-04-28 17:35 UTC, Artem2186 commented on zdanovich_lesson_11/app/src/main/java/ru/zdanovich/handhSchoolHomework/views/ColumnChartView.kt
> +        val columnsCoordinatesDraw =
мудрено как-то, тут точно нельзя обойтись одним массивом типа текущих координат?
и его апдейтить при анимации?

2021-04-28 18:08 UTC, alex-zdns commented on zdanovich_lesson_11/app/src/main/res/layout/activity_main.xml
> +    <ru.zdanovich.handhSchoolHomework.views.ColumnChartView
вынес в дименсы

2021-04-28 18:09 UTC, alex-zdns commented on zdanovich_lesson_11/app/src/main/java/ru/zdanovich/handhSchoolHomework/views/ColumnChartView.kt
> +        val columnsCoordinatesDraw =
оставил один массив с текущими координатами, добавил массив с конечными вершинами

2021-05-08 05:16 UTC, Artem2186 approved these changes

2021-05-08 08:50 UTC, merged