zdanovich_lesson_3
alex-zdns/handh.school.homework pull request #5
Opened 2021-03-26 14:13 UTC by alex-zdns

Как лучше сделать тень под под жёлтой вьюшкой?

2021-04-01 18:10 UTC, Artem2186 requested changes
К тебе персональное задание - нужно сверстать еще на координаторе

2021-04-01 18:10 UTC, Artem2186 commented on zdanovich_lesson_3/app/src/main/java/ru/zdanovich/handhSchoolHomework/User.kt
> +        fun getSampleUser(): User = User(
было бы еще круче, если бы ты замутил отдельную сущность UserRepository, которая бы отдавала getUser()
ну и код по пакетам разбил ( почитай про CLEAN)

2021-04-01 18:10 UTC, Artem2186 commented on zdanovich_lesson_3/app/src/relative/res/layout/activity_user_info.xml
> +            <ImageView
вот тут не учел, что если текст в поле будет сильно большой - он подлезет под кнопку

2021-04-01 18:10 UTC, Artem2186 commented on zdanovich_lesson_3/app/src/constraint/res/layout/activity_user_info.xml
> +                android:id="@+id/aui_region_edit"
тут тоже не учел, что текст может подлазить под кнопку, если будет слишком большим

2021-04-04 13:43 UTC, alex-zdns commented on zdanovich_lesson_3/app/src/constraint/res/layout/activity_user_info.xml
> +                android:id="@+id/aui_region_edit"
теперь учел

2021-04-04 13:54 UTC, alex-zdns commented on zdanovich_lesson_3/app/src/relative/res/layout/activity_user_info.xml
> +            <ImageView
учел

2021-04-04 18:18 UTC, Artem2186 requested changes

2021-04-04 18:18 UTC, Artem2186 commented on zdanovich_lesson_3/app/src/coordinator/res/layout/activity_user_info.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
тогда координатор лучше здесь использовать, но по-хорошему, засунуть тулбар в appBarLayout 
Аппбару можно будет выставить elevation и тогда появится тенька

2021-04-04 18:22 UTC, Artem2186 requested changes

2021-04-04 18:22 UTC, Artem2186 commented on zdanovich_lesson_3/app/src/relative/res/layout/activity_user_info.xml
> +            <ImageView
так можно, но это костыль, у relative есть параметр, который привяжет конец вьюхи к началу следующей

2021-04-05 13:30 UTC, alex-zdns commented on zdanovich_lesson_3/app/src/relative/res/layout/activity_user_info.xml
> +            <ImageView
поправил

2021-04-05 13:31 UTC, alex-zdns commented on zdanovich_lesson_3/app/src/coordinator/res/layout/activity_user_info.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Перенес тулбар в appBarLayout. Но поместил его под карточкой, если разместить его над карточкой то не работает схлопывание.

2021-04-12 06:17 UTC, merged