zdanovich_lesson_4
alex-zdns/handh.school.homework pull request #6
Opened 2021-03-30 18:30 UTC by alex-zdns

2021-04-06 16:21 UTC, Artem2186 approved these changes

2021-04-06 16:21 UTC, Artem2186 commented on zdanovich_lesson_4/app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
тут лучше констреинт

2021-04-06 16:35 UTC, Artem2186 requested changes

2021-04-06 16:35 UTC, Artem2186 commented on zdanovich_lesson_4/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/ma_recycler_view"
тут маргин топовый стремно смотрится, можно сделать лучше через клиппирование и паддинг

2021-04-06 16:35 UTC, Artem2186 commented on zdanovich_lesson_4/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/ma_recycler_view"
ну и теньку на тулбар

2021-04-06 18:25 UTC, alex-zdns commented on zdanovich_lesson_4/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/ma_recycler_view"
теньку добавил. Что такое клиппирование? маргин заменил на паддинг, но ведь внешне ничего не изменилось. Чет не понимаю суть замечания(

2021-04-07 00:35 UTC, alex-zdns commented on zdanovich_lesson_4/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/ma_recycler_view"
![1](https://user-images.githubusercontent.com/60062287/113793951-23e11c80-9752-11eb-8d47-36c73d43d5c8.png)
Тип при скроле этого отступа быть не должно?

2021-04-07 07:38 UTC, alex-zdns commented on zdanovich_lesson_4/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/ma_recycler_view"
ну вроде разобрался

2021-04-17 05:13 UTC, Artem2186 approved these changes

2021-04-17 05:13 UTC, Artem2186 commented on zdanovich_lesson_4/app/src/main/java/ru/zdanovich/handhSchoolHomework/ui/myFlat/MainActivity.kt
> +            it.addItemDecoration(object : RecyclerView.ItemDecoration() {
по факту, бесполезен декоратор, всем ячейкам выставляется одинаковое значение отступов. Нужно сделать отступы везде одинаковыми

2021-04-17 12:20 UTC, merged