zdanovich_lesson_5
alex-zdns/handh.school.homework pull request #7
Opened 2021-04-04 13:25 UTC by alex-zdns

2021-04-12 19:30 UTC, Artem2186 requested changes

2021-04-12 19:30 UTC, Artem2186 commented on zdanovich_lesson_5/app/src/main/java/ru/zdanovich/handhSchoolHomework/ui/FourthActivity.kt
> +        val formatDate = SimpleDateFormat(DATE_PATTERN, Locale.getDefault())
Дейт формат лучше создавать как можно реже, он долго создается

2021-04-12 20:11 UTC, alex-zdns commented on zdanovich_lesson_5/app/src/main/java/ru/zdanovich/handhSchoolHomework/ui/FourthActivity.kt
> +        val formatDate = SimpleDateFormat(DATE_PATTERN, Locale.getDefault())
перенес в companion object

2021-04-13 19:59 UTC, Artem2186 approved these changes

2021-04-14 04:50 UTC, merged