zdanovich_lesson_6
alex-zdns/handh.school.homework pull request #8
Opened 2021-04-09 18:06 UTC by alex-zdns

2021-04-17 16:48 UTC, Artem2186 requested changes

2021-04-17 16:48 UTC, Artem2186 commented on zdanovich_lesson_6/app/src/main/res/layout/input_field.xml
> +        android:layout_height="42dp"
в дименсы

2021-04-17 16:48 UTC, Artem2186 commented on zdanovich_lesson_6/app/src/main/java/ru/zdanovich/handhSchoolHomework/ui/second/CommunalServiceAdapter.kt
> +        val binding = CommunalServiceCardBinding.inflate(layoutInflater, parent, false)
лучше таки разные холдеры использовать. Так ты нарушаешь  sOlid

2021-04-18 09:19 UTC, alex-zdns commented on zdanovich_lesson_6/app/src/main/res/layout/input_field.xml
> +        android:layout_height="42dp"
заменил на wrap_content

2021-04-18 09:19 UTC, alex-zdns commented on zdanovich_lesson_6/app/src/main/java/ru/zdanovich/handhSchoolHomework/ui/second/CommunalServiceAdapter.kt
> +        val binding = CommunalServiceCardBinding.inflate(layoutInflater, parent, false)
создал отдельные холдеры

2021-12-27 13:27 UTC, merged